var iconNames = [
  "Argorok.png",
  "Armogohma.png",
  "Arrows.png",
  "Ashei's Sketch.png",
  "Auru's Memo.png",
  "Ball and Chain.png",
  "Bedroom Key.png",
  "Blizzeta.png",
  "Blue Rupee.png",
  "Bomb Bag.png",
  "Bomblings.png",
  "Bombs.png",
  "Boss Chest.png",
  "Boss Door.png",
  "Boss DoorG.png",
  "Boss DoorL.png",
  "Boss DoorS.png",
  "Boss Key.png",
  "Boss KeyHC.png",
  "Bottle.png",
  "BottleBee.png",
  "BottleBlue.png",
  "BottleFairy.png",
  "BottleMilk.png",
  "BottleMilkH.png",
  "BottleNasty.png",
  "BottlePurple.png",
  "BottleRare.png",
  "BottleRed.png",
  "BottleSoup.png",
  "BottleTears.png",
  "BottleWater.png",
  "BottleWorm.png",
  "BottleYellow.png",
  "Bow0.png",
  "Bow1.png",
  "Bow2.png",
  "Bug0.png",
  "Bug1.png",
  "Bug10.png",
  "Bug11.png",
  "Bug12.png",
  "Bug13.png",
  "Bug14.png",
  "Bug15.png",
  "Bug16.png",
  "Bug17.png",
  "Bug18.png",
  "Bug19.png",
  "Bug2.png",
  "Bug20.png",
  "Bug21.png",
  "Bug22.png",
  "Bug23.png",
  "Bug3.png",
  "Bug4.png",
  "Bug5.png",
  "Bug6.png",
  "Bug7.png",
  "Bug8.png",
  "Bug9.png",
  "Castle.png",
  "Chest.png",
  "Clawshot0.png",
  "Clawshot1.png",
  "Compass.png",
  "Controller.png",
  "Coral Earring.png",
  "Diababa.png",
  "Dominion Rod0.png",
  "Dominion Rod1.png",
  "Door.png",
  "Dungeon Map.png",
  "Dungeon Star.png",
  "Entrance.png",
  "Fishing Rod0.png",
  "Fishing Rod1.png",
  "Fused Shadow.png",
  "Fyrus.png",
  "Gale Boomerang.png",
  "Ganondorf.png",
  "GBK0.png",
  "GBK1.png",
  "GBK2.png",
  "GBK3.png",
  "Giant Bomb Bag.png",
  "Golden Wolf.png",
  "Green Rupee.png",
  "Grotto.png",
  "Hawk Grass.png",
  "Hawkeye.png",
  "Heart Container Render.png",
  "Heart Container.png",
  "Heart Piece Render.png",
  "Heart Piece.png",
  "Hero's Bow.png",
  "Hidden Skill.png",
  "Horse Call.png",
  "Horse Grass.png",
  "Howling Stone.png",
  "Ilia's Charm.png",
  "Invoice.png",
  "Iron Boots.png",
  "ItemBox.png",
  "Lantern.png",
  "Lock.png",
  "Locked Door.png",
  "LockS.png",
  "Magic Armor.png",
  "MenuBox.png",
  "Midna.png",
  "Mirror Shard.png",
  "Mirror.png",
  "Morpheel.png",
  "Ooccoo.png",
  "OoccooPot.png",
  "Orange Rupee.png",
  "Ordon Goat Cheese.png",
  "Ordon Pumpkin.png",
  "Paper.png",
  "Poe Soul.png",
  "Postman.png",
  "Purple Rupee.png",
  "Quiver0.png",
  "Quiver1.png",
  "Quiver2.png",
  "Red Rupee.png",
  "Renado's Letter.png",
  "Rupee Boulder.png",
  "Rupees.png",
  "Scent0.png",
  "Scent1.png",
  "Scent2.png",
  "Scent3.png",
  "Scent4.png",
  "Seeds.png",
  "Settings.png",
  "Shadow Crystal.png",
  "Shield0.png",
  "Shield1.png",
  "Shield2.png",
  "Sign.png",
  "Silver Rupee.png",
  "Sky Book Character.png",
  "Slingshot.png",
  "Small Chest.png",
  "Small Key.png",
  "Small KeyB.png",
  "Small KeyC.png",
  "Small KeyG.png",
  "Small KeyHC.png",
  "Spinner.png",
  "Stallord.png",
  "Sword0.png",
  "Sword1.png",
  "Sword2.png",
  "Sword3.png",
  "Tracker.png",
  "Wallet0.png",
  "Wallet1.png",
  "Wallet2.png",
  "Water Bombs.png",
  "Wooden Statue.png",
  "Yellow Rupee.png",
  "Zant.png",
  "Zora Armor.png"
]